[functions]
  included_files = ["node_modules/express/**", "src/data/data.json"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[build]
  command = "pnpm build"
  functions = "dist/netlify/functions"